flatpak/flatpak-xdg-utils

- src/flatpak-spawn.c
The exit status in the HostCommandExited/SpawnExited signal is as returned by waitpid(), which is a combination of flags indicating the way in which the process exited (or was SIGSTOPed or SIGCONTed) and the exit code or signal number. The exact layout is platform-specific, but on Linux the gist is:
* on exit(x), the exit status is ((x & 0xff) << 8); the low byte is 0
* on being killed by signal y, the exit status is in the low byte, with its high bit (0x80) set if the process dumped core
The number passed to exit() is specified to be masked with 0xff to fall in the range [0, 255].
These are different numbers, so passing one where the other is expected does not work:
* A process that calls exit(1) has exit status 256 (0x0100). Since (0x0100 & 0xff) == 0, passing this to exit() means …
> spawn: fix propagating exit code

- src/flatpak-spawn.c
> Command name

- src/flatpak-spawn.c
Take out the misleading name and say what we do.
Also tweak the options descriptions.
> Improve help output

- src/flatpak-spawn.c
Three changes that make flatpak-spawn work as expected:
- Don't use a timeout of 0 in D-Bus calls, it doesn't work.
- Quit if we lose the session bus
- Add a --watch-bus option
Together, these fix the issues raised in #12
> Spawn issues

- .travis.yml
- meson.build
- meson_options.txt
- src/backport-autoptr.h
- src/flatpak-spawn.c
- tests/ci-Dockerfile.in
- tests/ci-build.sh
- tests/ci-install.sh
- tests/common.c
- tests/common.h
- tests/meson.build
- tests/template-tap.test.in
- tests/test-email.c
- tests/test-open.c
I'm looking into adding flatpak-xdg-utils to Debian, so that we can build containers from Debian packages and have them talk to xdg-desktop-portal on the host system. For boring administrative reasons it's easier to add as-installed tests in the first upload of a new Debian package than to upload it without tests and add them later, so here's some basic test coverage.
This doesn't cover anything particularly fancy yet, and also doesn't yet cover flatpak-spawn at all, but it's a good starting point for not regressing.
I'm not sure how backwards-compatible these tools are meant to be, but it seems to be straightforward to make them work on Ubuntu 14.04 LTS (GLib 2.40), so I've added the necessary g_autoptr glue to let people backport the package to Ubuntu 14.04, Debian 9 or contemporary …
> Add g_autoptr backports, basic test coverage, and Travis-CI

- src/flatpak-spawn.c
This allows invoking a command in a directory that is not necessarily
visible from inside a sandbox
> Add option to flatpak-spawn to specify the working dir of a command

- src/xdg-email.c
- src/xdg-open.c
g_option_context_add_main_entries() is documented to take an array of
GOptionEntry, terminated by a NULL-filled entry; however, these tools
did not terminate the array.
In practice it appears that current toolchains place enough zero bytes
after the array that this worked as intended on most architectures, but
this is not the case on the Debian mips64el and riscv64 ports.
> xdg-email, xdg-open: Terminate GOptionEntry array correctly

- src/flatpak-spawn.c
This adds support for the new sandbox-flags and expose-fd[-ro] features
in flatpak. 
These are currently being handled here: https://github.com/flatpak/flatpak/pull/3248 and this should not be merged until that lands.
> Support new sandbox portal features

- meson.build
- src/flatpak-spawn.c
- src/meson.build
signal(2) is annoying to use because the signal handler is restricted
to a limited set of async-signal-safe functions (see signal-safety(7)).
For example, the signal handler might be called while the same thread
is halfway through a call to malloc(), so it is not necessarily safe
for it to allocate memory - which is a problem, because g_idle_add()
almost certainly allocates memory.
Solving this portably would require tricky Unix code like the
implementation that's behind g_unix_signal_source_new() (which we
can't use directly here, because it is documented not to support
SIGQUIT, SIGCONT or SIGTSTP). However, Flatpak is Linux-specific, and
Linux since at least 2.6.27 (2008) implements signalfd(), which delivers
signals into a poll()-based main loop - exactly what we want here.
Resolves: …
> flatpak-spawn: Make signal handling async-signal-safe

- src/flatpak-spawn.c
* flatpak-spawn: Use exit code 70 for weird wait-statuses as intended
The original implementation mistakenly reset exit_status instead of
exit_code. This originally left exit_code undefined, with subsequent
commit 50991f5f "Fix (bogus) uninitialized use warning" changing the
undefined exit code to 0.
Revert 50991f5f, because the warning turned out not to have
been bogus, and should be silenced by this change.
Fixes: 54c5800f "spawn: fix propagating exit code"
* flatpak-spawn: Clarify a variable name
I usually find that code dealing with POSIX-style exit statuses is
clearer if we distinguish between a "wait status" (what wait() or
waitpid() gives us, referred to as "wstatus" in Linux wait(2))
and an "exit status" (what we pass to exit(3), or equivalently, what
we can extract from a wait …
> flatpak-spawn: Fix exit status on seeing a weird wait-status

- .travis.yml
- meson.build
- src/xdg-email.c
- tests/ci-install.sh
- tests/meson.build
- tests/test-email.c
The reference xdg-email shell script documents that it supports mailto:
URIs, and it appears that at least Chromium and Jami (formerly GNU Ring)
genuinely make use of that feature.
If the only non-ignored argument is a mailto: URI, we pass it
directly to the OpenURI portal without further processing. This mode
can be used by applications wishing to do tricky things with headers
that we don't directly support.
Otherwise, we parse the mailto: URI and extract the header, subject
and addresses. Other headers are ignored.
The reference xdg-email script only accepts one mailto: URI, but
accepting more than one is actually easier than not, so we do that.
Resolves: https://github.com/flatpak/flatpak-xdg-utils/issues/19
---
Branch based on #31 to get the tests to pass. Only the last commit is new …
> xdg-email: Accept mailto: URIs

- .travis.yml
- meson.build
- src/xdg-email.c
- tests/ci-install.sh
- tests/meson.build
- tests/test-email.c
The addition of Email v3 support in 0c2b15c7 caused the automated tests to fail. This was not completely deterministic, because it depended on uninitialized stack contents; for me, it reliably failed on Debian 10 (and on Travis-CI) but passed on Debian testing/unstable.
The important fix here is "xdg-email: Cope gracefully with version being unavailable or wrong type", which could be cherry-picked if there are problems with the rest.
* CI: Install a newer version of Ninja for Ubuntu 16.04, too
The latest version of Meson requires a newer version of Ninja than
the one available in Ubuntu 16.04.
* Use Ubuntu 18.04 rather than 16.04 for CI
* build: Request C99, with GNU extensions
Otherwise inline declarations like "for (int i = 0; ...)" are an error.
* xdg-email: Cope gracefully with …
> Fix test failures caused by Email v3 support

- src/xdg-open.c
As of xdg-desktop-portal 1.8.0, the writable checks become far more
strict, meaning that passing an O_PATH fd that the current application
has write access to without declaring that it should be writable will
result in the open failing. This drops O_PATH in favor of the new
standard fd support, and opens the descriptor as read-only to match
the GLib behavior.
Fixes flatpak/flatpak#3879.
> xdg-open: Avoid the use of O_PATH fds

- src/flatpak-spawn.c
* #42 (please see that PR for details)
* flatpak-spawn: Add an --unset-env option
For now, this is just syntactic sugar for prepending env(1) to the
command we run, but adding new API to flatpak-portal will let us stop
doing that.
* flatpak-spawn: Use unset-env option if subsandbox portal >= v5
---
This is a client-side for flatpak/flatpak@c4a58d58, with a fallback implementation in terms of `env -u` that is used on older flatpak versions or with `--host`.
Based on code that I wrote for Steam's pressure-vessel-launch, a tool to launch subprocesses from an IPC server inside a container, which in turn is based on flatpak-spawn.
> Add --unset-env option

- tests/meson.build
- tests/test-spawn.c
This doesn't yet cover --env-fd, forwarding signals, or some of the
harder-to-provoke error cases, but it's enough for almost 75% line
coverage, which is a good start.
> Add basic test coverage for flatpak-spawn

- src/xdg-email.c
xdg-desktop-portal 0.9 switched from attachments as an array of URIs to
attachment_fds as an array of fds, but flatpak-xdg-utils 1.0.0 switched
from attachments as an array of URIs to attachments as an array of ints
(not fds!), resulting in failure to interoperate.
Fixes: f8ed903c "email: Pass attachments as fds"  
Resolves: #50
> xdg-email: Send attachments using the correct option name and type

- src/flatpak-spawn.c
Preparatory work for supporting https://github.com/flatpak/flatpak/pull/4018
---
* flatpak-spawn: Factor out path_to_handle()
This will let us deal with arguments that are a single path, instead
of a GStrv of paths.
* flatpak-spawn: Try to normalize exposed paths to be in ~/.var/app
The Flatpak portal will reject paths that do not resolve to the same
thing in the container and on the host system. For example,
--sandbox-expose-path="$HOME/.config/my/file"
will not work, even if
--sandbox-expose-path="$HOME/.var/app/com.example.App/config/my/file"
would.
Existing apps like GNOME Web (Epiphany) get away with this because the
files they are exposing are below $XDG_CONFIG_HOME, $XDG_DATA_HOME or
$XDG_CACHE_HOME, which take values below ~/.var/app, but the same is
not necessarily going to be …
> Factor out and improve path_to_handle()

- src/flatpak-spawn.c
- tests/common.c
- tests/common.h
- tests/test-spawn.c
Based on the refactoring from #38.
---
* #38 
* flatpak-spawn: Add the ability to set a custom path for /app or /usr
This is a client-side for
<https://github.com/flatpak/flatpak/pull/4018>.
Steam's pressure-vessel tool does the equivalent of this to launch
a parallel container with /usr supplied by the Steam Runtime, and an
empty /app, although currently it has to use code derived from
flatpak-spawn rather than using the runtime's copy of flatpak-spawn.
* test-spawn: Check contents of options dict more extensibly
Instead of asserting that there is a hard-coded number of items in the
dict, count how many items we have checked and then assert that there
are no extra items left over at the end. This will make it easier to
test more options that add more items.
* tests: Exercise …
> flatpak-spawn: Add the ability to set a custom path for /app or /usr

- src/flatpak-spawn.c
Before:
```
[📦 org.gnome.Recipes flatpak-xdg-utils]$ ./_build/src/flatpak-spawn --share-pids true
--share-pids not supported by host portal
```
After:
```
[📦 org.gnome.Recipes flatpak-xdg-utils]$ ./_build/src/flatpak-spawn --share-pids true
--share-pids not supported by host portal
This feature requires Flatpak to be using a bubblewrap (bwrap) executable
that is not setuid root.
The non-setuid version of bubblewrap requires a kernel that allows
unprivileged users to create new user namespaces.
For more details please see:
https://github.com/flatpak/flatpak/wiki/User-namespace-requirements
```
> spawn: Print a more explanatory message when bwrap is setuid

- src/flatpak-portal.h
- src/flatpak-session-helper.h
- src/flatpak-spawn.c
This assumes <https://github.com/flatpak/flatpak/pull/4531> is applied.
> flatpak-spawn: Use headers copied from Flatpak for most constants

- src/flatpak-spawn.c
Spotted while adding test coverage to Steam's `steam-runtime-launch-client` (formerly `pressure-vessel-launch`), which is derived from `flatpak-spawn`.
> flatpak-spawn: Fix memory leak when receiving NameOwnerChanged

- src/flatpak-spawn.c
If `flatpak-spwan --host` fails, it now shows a message that thee Flatpak needs to permission to talk to org.freedesktop.Flatpak.  This would make it more clear for people who are new to Flatpak and have read, that you can execute host commands with `flatpak-spawn`.
> Show permission hint for flatpk-spawn --host

- src/flatpak-spawn.c
This is the flatpak-spawn counterpart to the new option of the Flatpak portal.
See https://github.com/flatpak/flatpak/pull/5898
> flatpak-spawn: Add "--sandbox-a11y-own-name"

- .github/workflows/check.yml
Version 3 of the action was deprecated on 2025-01-30, see https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Github workflow: update upload-artifact action to v4

- src/xdg-open.c
The 'ask' option was introduced in version 3 of the org.freedesktop.portal.OpenURI.{OpenURI,OpenFile} interface.
If false (the default), the portal may use a default application or pick the last choice.
> xdg-open: add an 'ask' option to force going through the application chooser
